<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Version>0.1.0</Version>
    <OutputType>Exe</OutputType>
    <GenerateFullPaths>true</GenerateFullPaths>
    <Nullable>annotations</Nullable>
    <Deterministic>true</Deterministic>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <DebugType Condition="'$(Configuration)'=='Debug'">portable</DebugType>
    <DebugSymbols Condition="'$(Configuration)'=='Debug'">true</DebugSymbols>
    <CopyLocalLockFileAssemblies Condition="'$(Configuration)'=='Debug'">true</CopyLocalLockFileAssemblies>
    <PreserveCompilationContext Condition="'$(Configuration)'=='Debug'">true</PreserveCompilationContext>
    <UserSecretsId>cc495ebc-d983-42ed-8b3c-2beb14443922</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Logs\**" />

    <Content Include="mvc.sitemap" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    <Content Update="package.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="package-lock.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="wwwroot\Content\**" CopyToPublishDirectory="Never" />
    <Content Update="wwwroot\Scripts\**" CopyToPublishDirectory="Never" />
	<Content Update="wwwroot\Content\**\*.woff" CopyToPublishDirectory="Always" />
	<Content Update="wwwroot\Content\**\*.woff2" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Scripts\Public\**" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Content\Public\**" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Scripts\Private\**" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Content\Private\**" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Scripts\Application\**\*.min.js" CopyToPublishDirectory="Always" />
    <Content Update="wwwroot\Content\Application\**\*.min.css" CopyToPublishDirectory="Always" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NonFactors.Grid.Mvc6" Version="7.0.0" />
    <PackageReference Include="NonFactors.Lookup.Mvc6" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppLogistics.Controllers\AppLogistics.Controllers.csproj" />
  </ItemGroup>

  <Target Name="PrePublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm ci" />
    <Exec Command="npm run build" />
  </Target>

</Project>
